/**
  * Author: LC5741501
  * Created Date: 26/02/26
  * Class path "tests/PayTransfer/HK_BulkCollection.spects"
  * Description: This Specification contains the test cases related HongKong Bulk Collection
  * 1) TC001_HK_BulkCollection - Verify creating a Bulk collection with new Payer
  * 2) TC002_HK_BulkCollection - Verify creating a Bulk collection with new Payer(existing and new Payer)
  */

//Required Imports
import { test, expect } from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
import { NavigatePages, PaymentsPages } from '../../../pages/IDEALX/index';
import { LoginPage } from '../../../pages/IDEALX/LoginPage';

//Initialize Web Component class
const webComponents = new WebComponents();

// Variable internalReferenceBoolean default true 
let internalReferenceBoolean = true;

// Variable amountSGDIsEdit default true 
let amountSGDIsEdit = true;

// Variable yourAccountDeductedEdited default true 
let yourAccountDeductedEdited = true;

// Variable internalReferenceAutoGenerated default true 
let internalReferenceAutoGenerated =true;


// --- Load JSON test data ---
const testDataPath = path.resolve(__dirname, '../../../data/HK_testData.json');
const  testData  = JSON.parse(fs.readFileSync(testDataPath, 'utf-8'));
import { chromium, Browser } from 'playwright';
import { WebComponents } from '../../../lib/components';

//Variable declaration for Browser
let customBrowser: Browser;

const loginCompanyId = testData.BulkCollection.SIT.loginCompanyId;
const loginUserId    = testData.BulkCollection.SIT.loginUserId;
const fromAccount    = testData.BulkCollection.SIT.fromAccount;
const payeeBankID    = testData.payer1.payeeBankID;

// Configure retries like the old Protractor suite
test.describe.configure({
  retries: Number(process.env.CASE_RETRY_TIMES ?? 0),
});

// Actions for beforEach and afterEach test hooks
test.describe('HK_BulkCollection (Playwright using PaymentsPages)', () => {
  let pages: PaymentsPages;
  // Track created payees per test
  type CreatedPayee = { nickName?: string; accountNumber?: string };
  let createdPayees: CreatedPayee[] = [];
   
  /**
   * This method run's before every testcase execution to launch the browser/page
   */ 
  test.beforeEach(async ({ page }, testInfo) => {
    // This is used by the logging proxies in some converted classes (optional)
    process.env.currentTestTitle = testInfo.title;
    customBrowser = await chromium.launch({ headless: false });
    test.setTimeout(200_000);
    const loginPage = new LoginPage(page);
    await loginPage.goto();
    await loginPage.login(loginCompanyId, loginUserId, '123');
    // 2) Create the aggregator once per test
    pages = new PaymentsPages(page);
    
  });

  /**
   * This method run's after every testcase execution to do the 
   * cleanup activity or to close any open connections
   */ 
  test.afterEach(async ({ page }, testInfo) => {
  // Only cleanup if the test passed
  if (testInfo.status !== 'passed') {
    console.warn(`[cleanup] Skipping payee deletion because test status is ${testInfo.status}`);
    return;
    }
    
  // Best-effort cleanup; never fail the test because cleanup failed
  for (const p of createdPayees) {
    try {
      const key = p.nickName ?? p.accountNumber ?? '';
      await pages.PayrollPage.deletePayeeByFilter(key, /* confirm */ true);
      console.log(`[cleanup] Deleted payee with key: ${key}`);
    } catch (err) {
      console.warn('[cleanup] Failed to delete a payee:', err);
    }
  }
  });
  
  //TC001_HK_BulkCollection
  test('TC001_HK_BulkCollection - Verify creation of a Bulk collection with new Payer', async ({ page }) => {

    //Step 1: Navigate Payment & Transfer Menu.
    await pages.AccountTransferPage.waitForMenu();
    await webComponents.clickWhenVisibleAndEnabledCustomWait(pages.AccountTransferPage.paymentMenu,15_000);

    //Step 2: Handle Authentication Pop-up.
    await pages.AccountTransferPage.handleAuthIfPresent("1111")

    // Step 3: Click Bulk Collection option.
    await webComponents.clickWhenVisibleAndEnabledCustomWait(pages.BulkCollectionPage.bulkCollection,15_000);
    await pages.BulkCollectionPage.waitForBulkCollectionFormReady();

    // Step 4: Select account from "Account" dropdown.
    await webComponents.clickWhenVisibleAndEnabledCustomWait(pages.BulkCollectionPage.fromAccount,15_000);
    await page.keyboard.type(fromAccount);
    await page.keyboard.press('ArrowDown');
    await page.keyboard.press('Enter');

    // Step 5: Select Credit Type: Itemized Credit.
    await webComponents.clickWhenVisibleAndEnabledCustomWait(pages.BulkCollectionPage.creditType);
    await webComponents.clickWhenVisibleAndEnabledCustomWait(pages.BulkCollectionPage.creditTypeValueItemizedCredit);

    // Step 6: Add "New payer".
    const {accountNumber }  = await pages.BulkCollectionPage.addNewPayerWithAllDetails({
      name: testData.payer1.newPayeeName,
      bankId: payeeBankID,
      accountNumber: testData.payer1.newPayeeAcctNumber,
      DDAReferenceNo: testData.payer1.DDAReference,
      MandateID: testData.payer1.mandateID
    });

    // Register for cleanup
    createdPayees.push({accountNumber });

    // Step 7: Enter Amount (SGD), Transaction code, Purpose of Payment and other optional details for 
    // Particulars, Collection details to the payer bank, Message to the payee, Emails, Emails Message.
    await pages.BulkCollectionPage.enterNewPayerAmountAndOptionalDetails(testData);

    // Step 8: Select Payment date.
    await webComponents.clickWhenVisibleAndEnabled(pages.BulkCollectionPage.earliestAvailableDateCheckbox);

    // Step 9: Click Next button.
    await webComponents.clickWhenVisibleAndEnabled(pages.BulkCollectionPage.nextButton);
    await pages.BulkCollectionPage.waitForPreviewPageReady();

    // Step 10: Click Submit button.
    await webComponents.clickWhenVisibleAndEnabled(pages.BulkCollectionPage.submitButton);
    await pages.BulkCollectionPage.waitForSubmittedPageReady();

    // Step 11: Get the full banner text.
    const referenceText = await pages.BulkCollectionPage.getReferenceText();
    console.log('Captured reference text:', referenceText);
    // It extracts the EBLV… token/Refrence no
    const reference = await pages.BulkCollectionPage.getReferenceID();
    console.log('Captured referenceID:', reference);

    // Step 12: Click Finish button.
    await webComponents.clickWhenVisibleAndEnabled(pages.BulkCollectionPage.finishButton);
    await pages.BulkCollectionPage.waitForPayAndTransferPageReady();
    
    // Step 13: Search Reference No and Open.
    await pages.TransferCentersPage.searchAndOpenByReference(reference);
    await pages.BulkCollectionPage.waitForViewPaymentPageReady();
    
    // Step 14: Validate the Reference No details.
    // This method validates the existing PayeeOrReferenceNo Details.
    await pages.BulkCollectionPage.validatePayerOrRefrenceNoDetailsOfBulkCollection(testData, reference);

    // Step 15: This method deletes the existing opened PayeeOrReferenceNo.
    await pages.BulkCollectionPage.deleteOpenPayerOrReferenceNo(testData, reference);

  });


  //TC002_HK_BulkCollection
  test('TC002_HK_BulkCollection - Verify creation of a Bulk collection with new and existing payer', async ({ page }) => {
    
    //Step 1: Navigate Payment & Transfer Menu.
    await pages.AccountTransferPage.waitForMenu();
    await webComponents.clickWhenVisibleAndEnabledCustomWait(pages.AccountTransferPage.paymentMenu,15_000);

    //Step 2: Handle Authentication Pop-up.
    await pages.AccountTransferPage.handleAuthIfPresent("1111")

    // Step 3: Click Bulk Collection option.
    await webComponents.clickWhenVisibleAndEnabledCustomWait(pages.BulkCollectionPage.bulkCollection,15_000);
    await pages.BulkCollectionPage.waitForBulkCollectionFormReady();

    // Step 4: Select account from "Account" dropdown.
    await webComponents.clickWhenVisibleAndEnabledCustomWait(pages.BulkCollectionPage.fromAccount,15_000);
    await page.keyboard.type(fromAccount);
    await page.keyboard.press('ArrowDown');
    await page.keyboard.press('Enter');

    // Step 5: Select Credit Type: Consolidated Credit.
    await webComponents.clickWhenVisibleAndEnabledCustomWait(pages.BulkCollectionPage.creditType);
    await webComponents.clickWhenVisibleAndEnabledCustomWait(pages.BulkCollectionPage.creditTypeValueConsolidatedCredit);

    // Step 6: Add Existing Payer.
    await webComponents.enterTextarea(pages.BulkCollectionPage.filterExistingPayee, testData.payer2.newPayeeName);
    await webComponents.clickWhenVisibleAndEnabledCustomWait(pages.BulkCollectionPage.addButton);

    // Step 7: Add Existing Payer: Amount, Transaction code and Particulars
    await pages.BulkCollectionPage.enterExtistingPayerAmountTransactionCodeAndParticulars(testData);

     // Step 8: Add "New payer".
    const {accountNumber }  = await pages.BulkCollectionPage.addNewPayerWithAllDetails({
      name: testData.payer1.newPayeeName,
      bankId: payeeBankID,
      accountNumber: testData.payer1.newPayeeAcctNumber,
      DDAReferenceNo: testData.payer1.DDAReference,
      MandateID: testData.payer1.mandateID
    });

    // Register for cleanup
    createdPayees.push({accountNumber });

    // Step 9: Enter Amount (SGD), Transaction code, Purpose of Payment and other optional details for 
    // Particulars, Collection details to the payer bank, Message to the payee, Emails, Emails Message.
    await pages.BulkCollectionPage.enterNewPayerAmountOptionalDetailsWhenExistingPayerAdded(testData);

    // Step 8: Select Payment date: Earliest Available Date.
    await webComponents.clickWhenVisibleAndEnabled(pages.BulkCollectionPage.earliestAvailableDateCheckbox);
    
    // Step 9: Click Next button.
    await webComponents.clickWhenVisibleAndEnabled(pages.BulkCollectionPage.nextButton);
    await pages.BulkCollectionPage.waitForPreviewPageReady();

    // Step 10: Click Submit button.
    await webComponents.clickWhenVisibleAndEnabled(pages.BulkCollectionPage.submitButton);
    await pages.BulkCollectionPage.waitForSubmittedPageReady();

    // Step 11: Get the full banner text.
    const referenceText = await pages.BulkCollectionPage.getReferenceText();
    console.log('Captured reference text:', referenceText);
    // It extracts the EBLV… token/Refrence no
    const reference = await pages.BulkCollectionPage.getReferenceID();
    console.log('Captured referenceID:', reference);

    // Step 12: Click Finish button.
    await webComponents.clickWhenVisibleAndEnabled(pages.BulkCollectionPage.finishButton);
    await pages.BulkCollectionPage.waitForPayAndTransferPageReady();
    
    // Step 13: Search Reference No and Open.
    await pages.TransferCentersPage.searchAndOpenByReference(reference);
    await pages.BulkCollectionPage.waitForViewPaymentPageReady();
    
    // Step 14: Validate the Reference No details.
    await pages.BulkCollectionPage.validatePayer2ConsolidateValueInBulkCollection(testData, reference);

    // Step 15: This method deletes the existing opened PayeeOrReferenceNo.
    await pages.BulkCollectionPage.deleteOpenPayerOrReferenceNo(testData, reference);

  });

});