/**
  * Author: LC5741501
  * Created Date: 26/02/26
  * Class path "tests/PayTransfer/HK_BulkCollection.spects"
  * Description: This Specification contains the test cases related HongKong Bulk Collection
  * 1) TC001_HK_BulkCollection - Verify creating a Bulk collection with new Payer
  * 2) TC002_HK_BulkCollection - Verify creating a Bulk collection with new Payer(existing and new Payer)
  */

//Required Imports
import { test, expect } from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
import { NavigatePages, PaymentsPages } from '../../../pages/IDEALX/index';
import { LoginPage } from '../../../pages/IDEALX/LoginPage';
import { CONSTANTS } from '../../../lib/constants';
import { TIMEOUT } from '../../../lib/timeouts';

//Initialize Web Component class
const webComponents = new WebComponents();

// Variable internalReferenceBoolean default true 
let internalReferenceBoolean = true;

// Variable amountSGDIsEdit default true 
let amountSGDIsEdit = true;

// Variable yourAccountDeductedEdited default true 
let yourAccountDeductedEdited = true;

// Variable internalReferenceAutoGenerated default true 
let internalReferenceAutoGenerated = true;


// --- Load JSON test data ---
const testDataPath = path.resolve(__dirname, '../../../data/HK_testData.json');
const testData = JSON.parse(fs.readFileSync(testDataPath, 'utf-8'));
import { chromium, Browser } from 'playwright';
import { WebComponents } from '../../../lib/components';

//Variable declaration for Browser
let customBrowser: Browser;

const loginCompanyId = testData.BulkCollection.SIT.loginCompanyId;
const loginUserId = testData.BulkCollection.SIT.loginUserId;
const fromAccount = testData.BulkCollection.SIT.fromAccount;
const payeeBankID = testData.payer1.payeeBankID;

// Configure retries like the old Protractor suite
test.describe.configure({
  retries: Number(process.env.CASE_RETRY_TIMES ?? 0),
});

// Actions for beforEach and afterEach test hooks
test.describe('HK_BulkCollection (Playwright using PaymentsPages)', () => {
  let pages: PaymentsPages;
  // Track created payees per test
  type CreatedPayee = { nickName?: string; accountNumber?: string };
  let createdPayees: CreatedPayee[] = [];

  /**
  * This method run's before every testcase execution to launch the browser/page
  */
  test.beforeEach(async ({ page }, testInfo) => {
    process.env.currentTestTitle = testInfo.title;

    //customBrowser = await chromium.launch({ headless: false });
    test.setTimeout(TIMEOUT.MAX);
    const loginPage = new LoginPage(page);
    await loginPage.goto();
    await loginPage.login(loginCompanyId, loginUserId, (String(CONSTANTS.PIN)));

    pages = new PaymentsPages(page);
  });

  /**
  * This method run's after every testcase execution to do the 
  * cleanup activity or to close any open connections
  */
  test.afterEach(async ({ page }, testInfo) => {
    // Only cleanup if the test passed
    if (testInfo.status !== 'passed') {
      console.warn(`[cleanup] Skipping payee deletion because test status is ${testInfo.status}`);
      return;
    }

    // Best-effort cleanup; never fail the test because cleanup failed
    for (const p of createdPayees) {
      try {
        const key = p.nickName ?? p.accountNumber ?? '';
        await pages.PayrollPage.deletePayeeByFilter(key, /* confirm */ true);
        console.log(`[cleanup] Deleted payee with key: ${key}`);
      } catch (err) {
        console.warn('[cleanup] Failed to delete a payee:', err);
      }
    }
  });

  //TC001_HK_BulkCollection
  test('TC001_HK_BulkCollection - Verify creation of a Bulk collection with new Payer', async ({ page }) => {

    //Step 1: Navigate Payment & Transfer Menu.
    await webComponents.waitForUXLoading([], page);
    await webComponents.waitElementToBeVisible(pages.AccountTransferPage.paymentMenu);
    await webComponents.clickWhenVisibleAndEnabled(pages.AccountTransferPage.paymentMenu);

    //Step 2: Handle Authentication Pop-up.
    await webComponents.handleAuthIfPresent(pages.AccountTransferPage.authDialog, pages.AccountTransferPage.securityAccessCode, pages.AccountTransferPage.authenticateButton);

    // Step 3: Click Bulk Collection option.
    await webComponents.clickWhenVisibleAndEnabled(pages.BulkCollectionPage.bulkCollection);
    await webComponents.waitForUXLoading([], page);
    await webComponents.waitElementToBeVisible(pages.BulkCollectionPage.fromAccount);
    await webComponents.clickWhenVisibleAndEnabled(pages.BulkCollectionPage.fromAccount);

    // Step 4: Select account from "Account" dropdown.
    await webComponents.clickWhenVisibleAndEnabled(pages.BulkCollectionPage.fromAccount);
    await webComponents.typeTextThroughKeyBoardAction(page, fromAccount);
    await webComponents.pressGivenButtonThroughKeyBoardAction(page, 'ArrowDown');
    await webComponents.pressGivenButtonThroughKeyBoardAction(page, 'Enter');

    // Step 5: Select Credit Type: Itemized Credit.
    await webComponents.clickWhenVisibleAndEnabled(pages.BulkCollectionPage.creditType);
    await webComponents.clickWhenVisibleAndEnabled(pages.BulkCollectionPage.creditTypeValueItemizedCredit);

    // Step 6: Add "New payer".
    const { accountNumber } = await pages.BulkCollectionPage.addNewPayerWithAllDetails({
      name: testData.payer1.newPayeeName,
      bankId: payeeBankID,
      accountNumber: testData.payer1.newPayeeAcctNumber,
      DDAReferenceNo: testData.payer1.DDAReference,
      MandateID: testData.payer1.mandateID
    });

    // Register for cleanup
    createdPayees.push({ accountNumber });

    // Step 7: Enter Amount (SGD), Transaction code, Purpose of Payment and other optional details for 
    // Particulars, Collection details to the payer bank, Message to the payee, Emails, Emails Message
    await pages.BulkCollectionPage.enterNewPayeeAllOtherDetails({
      amountPayer2Tc002: testData.payer1.amountPayer2Tc002,
      amount: testData.payer1.amount,
      transactionCode: testData.payer1.transactionCodeSelect,
      purposeOfPayment: testData.payer1.purposeOfPayment,
      particularsPayer1: testData.payer2.particularsPayer1,
      particulars: testData.payer1.particulars,
      collectionDetailsPayer1: testData.payer2.collectionDetailsPayer1,
      collectionDetails: testData.payer1.collectionDetails,
      email1: testData.payer1.emailId0,
      email2: testData.payer1.emailId1,
      email3: testData.payer1.emailId2,
      email4: testData.payer1.emailId3,
      email5: testData.payer1.emailId4,
      emailMessage: testData.payer1.emailMessage
    });

    // Step 8: Select Payment date.
    await webComponents.clickWhenVisibleAndEnabled(pages.BulkCollectionPage.earliestAvailableDateCheckbox);

    // Step 9: Click Next button.
    await webComponents.clickWhenVisibleAndEnabled(pages.BulkCollectionPage.nextButton);
    await webComponents.waitForUXLoading([], page);
    await webComponents.waitElementToBeVisible(pages.BulkCollectionPage.submitButton);

    // Step 10: Click Submit button.
    await webComponents.clickWhenVisibleAndEnabled(pages.BulkCollectionPage.submitButton);
    await webComponents.waitForUXLoading([], page);
    await webComponents.waitElementToBeVisible(pages.BulkCollectionPage.finishButton);

    // Step 11: Get the full banner text.
    const referenceText = await pages.BulkCollectionPage.getReferenceText();
    console.log('Captured reference text:', referenceText);
    // It extracts the EBLV… token/Refrence no
    const reference = await pages.BulkCollectionPage.getReferenceID();
    console.log('Captured referenceID:', reference);

    // Step 12: Click Finish button.
    await webComponents.clickWhenVisibleAndEnabled(pages.BulkCollectionPage.finishButton);
    await webComponents.waitForUXLoading([], page);
    await webComponents.waitElementToBeVisible(pages.BulkCollectionPage.bulkCollection);

    // Step 13: Search Reference No and Open.
    await pages.TransferCentersPage.searchAndOpenByReference(reference);
    await webComponents.waitForUXLoading([], page);
    await webComponents.waitElementToBeVisible(pages.BulkCollectionPage.hashValue);
    await webComponents.waitElementToBeVisible(pages.BulkCollectionPage.toAccountNumberLabel);
    await webComponents.waitElementToBeVisible(pages.BulkCollectionPage.paymentTypeValue);

    // Step 14: Validate the Reference No details.
    await pages.BulkCollectionPage.validatePayeeOrRefrenceNoDetails({
      fromAccountValue1: testData.BulkCollectionValidationData.toAccountNumberLabel,
      fromAccountValue2: testData.BulkCollectionValidationData.toAccountNameLabel,
      paymentTypeValue: testData.BulkCollectionValidationData.paymentType,
      amountDeductedValue: testData.BulkCollectionValidationData.totalAmount,
      amountDeductedEditedValue: testData.BulkCollectionValidationData.totalAmountEditedValue,
      creditType: testData.BulkCollectionValidationData.creditType,
      referenceValueUserProvided: testData.BulkCollectionValidationData.internalReferenceUserProvided,
      batchIdValueUserProvided: testData.BulkCollectionValidationData.batchIdValueUserProvided,

      collectionSummaryLabel: testData.BulkCollectionValidationData.collectionSummaryLabel,
      totalPayeesLabel: testData.BulkCollectionValidationData.totalPayersLabel,
      totalPayeesValue: testData.BulkCollectionValidationData.totalPayersLabelValue,
      totalAmountLabel: testData.BulkCollectionValidationData.totalAmountLabel,
      totalAmountValue: testData.BulkCollectionValidationData.totalAmountLabelValue,
      totalAmountValueEdited: testData.BulkCollectionValidationData.totalAmountValueEdited,

      payeeNameLabelValue: testData.payer1.newPayeeName,
      payeeNicknameLabelValue: testData.payer1.newPayeeName,
      bankNameLabelValue: testData.BulkCollectionValidationData.bankNameValue,
      bankSwiftBicLabelValue: testData.BulkCollectionValidationData.bankCode,
      accountNumberLabelValue: testData.payer1.newPayeeAcctNumber,
      DDAReference: testData.payer1.DDAReference,
      statusLabelValue: testData.status.PendingApproval,

      amountLabelValue: testData.payer1.amount,
      amountEditedLabelValue: testData.payer1.amountEdited,
      transactionLabelValue: testData.payer1.transactionCode,
      purposeCodeLabelValue: testData.payer1.purposeOfPayment,
      particularsLabelValue: testData.payer1.particulars,
      collectionDetailsLabelValue: testData.payer1.collectionDetails,

      emailMessageLabelValue: testData.payer1.emailMessage,
      email1LabelValue: testData.payer1.emailId0,
      email2LabelValue: testData.payer1.emailId1,
      email3LabelValue: testData.payer1.emailId2,
      email4LabelValue: testData.payer1.emailId3,
      email5LabelValue: testData.payer1.emailId4
    }, reference);

    // Step 15: This method deletes the existing opened PayeeOrReferenceNo.
    await pages.BulkCollectionPage.deleteOpenPayerOrReferenceNo(testData, reference);

  });


  //TC002_HK_BulkCollection
  test('TC002_HK_BulkCollection - Verify creation of a Bulk collection with new and existing payer', async ({ page }) => {

    //Step 1: Navigate Payment & Transfer Menu.
    //await pages.AccountTransferPage.waitForMenu();
    await webComponents.waitForUXLoading([], page);
    await webComponents.waitElementToBeVisible(pages.AccountTransferPage.paymentMenu);
    await webComponents.clickWhenVisibleAndEnabled(pages.AccountTransferPage.paymentMenu);

    //Step 2: Handle Authentication Pop-up.
    //await pages.AccountTransferPage.handleAuthIfPresent("1111")
    await webComponents.handleAuthIfPresent(pages.AccountTransferPage.authDialog, pages.AccountTransferPage.securityAccessCode, pages.AccountTransferPage.authenticateButton);

    // Step 3: Click Bulk Collection option.
    await webComponents.clickWhenVisibleAndEnabled(pages.BulkCollectionPage.bulkCollection);
    //await pages.BulkCollectionPage.waitForBulkCollectionFormReady();
    await webComponents.waitForUXLoading([], page);
    await webComponents.waitElementToBeVisible(pages.BulkCollectionPage.fromAccount);

    // Step 4: Select account from "Account" dropdown.
    await webComponents.clickWhenVisibleAndEnabled(pages.BulkCollectionPage.fromAccount);
    //await page.keyboard.type(fromAccount);
    //await page.keyboard.press('ArrowDown');
    //await page.keyboard.press('Enter');
    await webComponents.typeTextThroughKeyBoardAction(page, fromAccount);
    await webComponents.pressGivenButtonThroughKeyBoardAction(page, 'ArrowDown');
    await webComponents.pressGivenButtonThroughKeyBoardAction(page, 'Enter');

    // Step 5: Select Credit Type: Consolidated Credit.
    await webComponents.clickWhenVisibleAndEnabled(pages.BulkCollectionPage.creditType);
    await webComponents.clickWhenVisibleAndEnabled(pages.BulkCollectionPage.creditTypeValueConsolidatedCredit);

    // Step 6: Add Existing Payer.
    await webComponents.enterTextarea(pages.BulkCollectionPage.filterExistingPayee, testData.payer2.newPayeeName);
    await webComponents.clickWhenVisibleAndEnabled(pages.BulkCollectionPage.addButton);

    // Step 7: Add Existing Payer: Amount, Transaction code and Particulars
    //await pages.BulkCollectionPage.enterExtistingPayerAmountTransactionCodeAndParticularsOLD(testData);

    // Step 7: Add Existing Payer: Amount, Transaction code and Particulars
    await pages.BulkCollectionPage.enterExtistingPayerAmountTransactionCodeAndParticulars({
      amount: testData.payer2.amount,
      transactionCode: testData.payer2.transactionCode,
      particulars: testData.payer2.particulars
    });

    // Step 8: Add "New payer".
    const { accountNumber } = await pages.BulkCollectionPage.addNewPayerWithAllDetails({
      name: testData.payer1.newPayeeName,
      bankId: payeeBankID,
      accountNumber: testData.payer1.newPayeeAcctNumber,
      DDAReferenceNo: testData.payer1.DDAReference,
      MandateID: testData.payer1.mandateID
    });

    // Register for cleanup
    createdPayees.push({ accountNumber });

    // Step 9: Enter Amount (SGD), Transaction code, Purpose of Payment and other optional details for 
    // Particulars, Collection details to the payer bank, Message to the payee, Emails, Emails Message.
    //await pages.BulkCollectionPage.enterNewPayerAmountOptionalDetailsWhenExistingPayerAdded(testData);


    // Step 9: Enter Amount (SGD), Transaction code, Purpose of Payment and other optional details for 
    // Particulars, Collection details to the payer bank, Message to the payee, Emails, Emails Message
    await pages.BulkCollectionPage.enterNewPayeeAllOtherDetails({
      amountPayer2Tc002: testData.payer2.amountPayer2Tc002,
      amount: testData.payer1.amount,
      transactionCode: testData.payer1.transactionCodeTc002,
      purposeOfPayment: testData.payer1.purposeOfPayment,
      particularsPayer1: testData.payer1.particularsPayer1,
      particulars: testData.payer1.particulars,
      collectionDetailsPayer1: testData.payer1.collectionDetailsPayer1,
      collectionDetails: testData.payer1.collectionDetails,
      email1: testData.payer1.emailId0,
      email2: testData.payer1.emailId1,
      email3: testData.payer1.emailId2,
      email4: testData.payer1.emailId3,
      email5: testData.payer1.emailId4,
      emailMessage: testData.payer1.emailMessage
    });

    // Step 10: Select Payment date: Earliest Available Date.
    await webComponents.clickWhenVisibleAndEnabled(pages.BulkCollectionPage.earliestAvailableDateCheckbox);

    // Step 11: Click Next button.
    await webComponents.clickWhenVisibleAndEnabled(pages.BulkCollectionPage.nextButton);
    //await pages.BulkCollectionPage.waitForPreviewPageReady();
    await webComponents.waitForUXLoading([], page);
    await webComponents.waitElementToBeVisible(pages.BulkCollectionPage.submitButton);

    // Step 12: Click Submit button.
    await webComponents.clickWhenVisibleAndEnabled(pages.BulkCollectionPage.submitButton);
    //await pages.BulkCollectionPage.waitForSubmittedPageReady();
    await webComponents.waitForUXLoading([], page);
    await webComponents.waitElementToBeVisible(pages.BulkCollectionPage.finishButton);

    // Step 13: Get the full banner text.
    const referenceText = await pages.BulkCollectionPage.getReferenceText();
    console.log('Captured reference text:', referenceText);
    // It extracts the EBLV… token/Refrence no
    const reference = await pages.BulkCollectionPage.getReferenceID();
    console.log('Captured referenceID:', reference);

    // Step 14: Click Finish button.
    await webComponents.clickWhenVisibleAndEnabled(pages.BulkCollectionPage.finishButton);
    //await pages.BulkCollectionPage.waitForPayAndTransferPageReady();
    await webComponents.waitForUXLoading([], page);
    await webComponents.waitElementToBeVisible(pages.BulkCollectionPage.bulkCollection);

    // Step 15: Search Reference No and Open.
    await pages.TransferCentersPage.searchAndOpenByReference(reference);
    //await pages.BulkCollectionPage.waitForViewPaymentPageReady();
    await webComponents.waitForUXLoading([], page);
    await webComponents.waitElementToBeVisible(pages.BulkCollectionPage.hashValue);
    await webComponents.waitElementToBeVisible(pages.BulkCollectionPage.toAccountNumberLabel);
    await webComponents.waitElementToBeVisible(pages.BulkCollectionPage.paymentTypeValue);

    // Step 14: Validate the Reference No details.
    //await pages.BulkCollectionPage.validatePayer2ConsolidateValueInBulkCollectionOLD(testData, reference);

    // Step 16: Validate the Reference No details.
    await pages.BulkCollectionPage.validatePayer2ConsolidateValueInBulkCollection({
      toAccountNumberLabel: testData.BulkCollectionValidationData.toAccountNumberLabel,
      toAccountNameLabel: testData.BulkCollectionValidationData.toAccountNameLabel,
      paymentTypeValue: testData.BulkCollectionValidationData.paymentType,
      totalAmountConsolidated: testData.BulkCollectionValidationData.totalAmountConsolidated,
      creditTypeConsolidated: testData.BulkCollectionValidationData.creditTypeConsolidated,
      referenceValueUserProvided: testData.BulkCollectionValidationData.internalReferenceUserProvided,
      batchIdValueUserProvided: testData.BulkCollectionValidationData.batchIdValueUserProvided,
      collectionSummaryLabel: testData.BulkCollectionValidationData.collectionSummaryLabel,

      totalPayeesLabel: testData.BulkCollectionValidationData.totalPayersLabel,
      totalPayersConsolidatedLabelValue: testData.BulkCollectionValidationData.totalPayersConsolidatedLabelValue,
      totalAmountLabel: testData.BulkCollectionValidationData.totalAmountLabel,

      totalAmountConsolidatedLabelValue: testData.BulkCollectionValidationData.totalAmountConsolidatedLabelValue,
      totalAmountValueEdited: testData.BulkCollectionValidationData.totalAmountValueEdited,

      payeeNameLabelValue: testData.payer1.newPayeeName,
      payeeNicknameLabelValue: testData.payer1.newPayeeName,
      bankNameLabelValue: testData.BulkCollectionValidationData.bankNameValue,
      bankSwiftBicLabelValue: testData.BulkCollectionValidationData.bankCode,
      accountNumberLabelValue: testData.payer1.newPayeeAcctNumber,
      DDAReference: testData.payer1.DDAReference,
      mandateID: testData.payer1.mandateID,
      statusLabelValue: testData.status.PendingApproval,

      amountLabelValue: testData.payer1.amount,
      amountEditedLabelValue: testData.payer1.amountEdited,
      transactionLabelValue: testData.payer1.transactionCodeTc002,
      purposeCodeLabelValue: testData.payer1.purposeOfPayment,
      particularsLabelValue: testData.payer1.particulars,
      collectionDetailsLabelValue: testData.payer1.collectionDetails,

      emailMessageLabelValue: testData.payer1.emailMessage,
      email1LabelValue: testData.payer1.emailId0,
      email2LabelValue: testData.payer1.emailId1,
      email3LabelValue: testData.payer1.emailId2,
      email4LabelValue: testData.payer1.emailId3,
      email5LabelValue: testData.payer1.emailId4,
      //Payer 2
      newPayeeName: testData.payer2.newPayeeName,
      newPayeeNickName: testData.payer2.newPayeeNickName,
      bankNameValue: testData.BulkCollectionValidationDataPayer2.bankNameValue,
      bankCodePayer2Value: testData.BulkCollectionValidationDataPayer2.bankCode,
      newPayeeAcctNumber: testData.payer2.newPayeeAcctNumber,
      DDAReferencePayer2: testData.payer2.DDAReference,
      mandateIDPayer2: testData.payer2.mandateID,
      bankCode: testData.payer2.PendingApproval,
      statusPayer2: testData.status.PendingApproval,
      amountPayer2: testData.payer2.amount,
      transactionCodePayer2: testData.payer2.transactionCode,
      particularsPayer2: testData.payer2.particulars,
    }, reference);

    // Step 17: This method deletes the existing opened PayeeOrReferenceNo.
    await pages.BulkCollectionPage.deleteOpenPayerOrReferenceNo(testData, reference);

  });

});