/**
  * Author: LC5741501
  * Created Date: 03/03/2026
  * Class path "tests/PayTransfer/HK_ManagementPayroll.spec.ts"
  * Description: This Specification contains the test cases related HongKong Management Payroll
  * 1) TC001_HK_ManagementPayroll - Verify creation of a Management Payroll with new Payee.
  */

//Required Imports
import { test, expect } from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
import { NavigatePages, PaymentsPages } from '../../../pages/IDEALX/index';
import { LoginPage } from '../../../pages/IDEALX/LoginPage';
import { CONSTANTS } from '../../../lib/constants';
import { TIMEOUT } from '../../../lib/timeouts';

//Initialize Web Component class
const webComponents = new WebComponents();

// Variable internalReferenceBoolean default true 
let internalReferenceBoolean = true;

// Variable amountSGDIsEdit default true 
let amountSGDIsEdit = true;

// Variable yourAccountDeductedEdited default true 
let yourAccountDeductedEdited = true;

// Variable internalReferenceAutoGenerated default true 
let internalReferenceAutoGenerated = true;


// --- Load JSON test data ---
const testDataPath = path.resolve(__dirname, '../../../data/HK_testData.json');
const testData = JSON.parse(fs.readFileSync(testDataPath, 'utf-8'));
import { chromium, Browser } from 'playwright';
import { WebComponents } from '../../../lib/components';

//Variable declaration for Browser
let customBrowser: Browser;

const loginCompanyId = testData.ManagePayroll.SIT.loginCompanyId;
const loginUserId = testData.ManagePayroll.SIT.loginUserIdHKMP;
const fromAccount = testData.ManagePayroll.SIT.fromAccount;

// Configure retries
test.describe.configure({
  retries: Number(process.env.CASE_RETRY_TIMES ?? 0),
});

// Actions for beforEach and afterEach test hooks
test.describe('HK_ManagementPayroll (Playwright using PaymentsPages)', () => {
  let pages: PaymentsPages;
  // Track created payees per test
  type CreatedPayee = { nickName?: string; accountNumber?: string };
  let createdPayees: CreatedPayee[] = [];

  /**
  * This method run's before every testcase execution to launch the browser/page
  */
  test.beforeEach(async ({ page }, testInfo) => {
    process.env.currentTestTitle = testInfo.title;

    //customBrowser = await chromium.launch({ headless: false });
    test.setTimeout(TIMEOUT.MAX);
    const loginPage = new LoginPage(page);
    await loginPage.goto();
    await loginPage.login(loginCompanyId, loginUserId, (String(CONSTANTS.PIN)));

    pages = new PaymentsPages(page);
  });

  /**
  * This method run's after every testcase execution to do the 
  * cleanup activity or to close any open connections
  */
  test.afterEach(async ({ page }, testInfo) => {
    // Only cleanup if the test passed
    if (testInfo.status !== 'passed') {
      console.warn(`[cleanup] Skipping payee deletion because test status is ${testInfo.status}`);
      return;
    }

    // Best-effort cleanup; never fail the test because cleanup failed
    for (const p of createdPayees) {
      try {
        const key = p.nickName ?? p.accountNumber ?? '';
        await pages.PayrollPage.deletePayeeByFilter(key, /* confirm */ true);
        console.log(`[cleanup] Deleted payee with key: ${key}`);
      } catch (err) {
        console.warn('[cleanup] Failed to delete a payee:', err);
      }
    }
  });

  //TC001_HK_ManagementPayroll
  test('TC001_HK_ManagementPayroll - Verify creation of a Management Payroll with new Payee', async ({ page }) => {

    //Step 1: Navigate Payment & Transfer Menu.
    await webComponents.waitForUXLoading([], page);
    await webComponents.waitElementToBeVisible(pages.AccountTransferPage.paymentMenu);
    await webComponents.clickWhenVisibleAndEnabled(pages.AccountTransferPage.paymentMenu);

    //Step 2: Handle Authentication Pop-up.
    await webComponents.handleAuthIfPresent(pages.AccountTransferPage.authDialog, pages.AccountTransferPage.securityAccessCode, pages.AccountTransferPage.authenticateButton);

    // Step 3: Click Management Payroll option.
    await webComponents.clickWhenVisibleAndEnabled(pages.PayrollPage.managePayroll);
    await webComponents.waitForUXLoading([], page);
    await webComponents.waitElementToBeVisible(pages.PayrollPage.fromAccount);

    // Step 4: Select account from "Account" dropdown.
    await webComponents.clickWhenVisibleAndEnabled(pages.PayrollPage.fromAccount);
    await webComponents.typeTextThroughKeyBoardAction(page, fromAccount);
    await webComponents.pressGivenButtonThroughKeyBoardAction(page, 'ArrowDown');
    await webComponents.pressGivenButtonThroughKeyBoardAction(page, 'Enter');

    // Step 5: Add "New payee".
    const { accountNumber } = await pages.PayrollPage.addNewPayeeWithAllDetails({
      name: testData.ManagePayrollPayer1.newPayeeName,
      nickName: testData.ManagePayrollPayer1.newPayeeNickName,
      bankId: testData.ManagePayrollPayer1.payeeBankID,
      accountNumber: testData.ManagePayrollPayer1.newPayeeAcctNumber
    });

    // Register for cleanup
    createdPayees.push({ accountNumber });

    // Step 6: Enter Amount (SGD), Transaction code, Purpose of Payment and other optional details for 
    // Particulars, Collection details to the payer bank, Message to the payee, Emails, Emails Message
    await pages.PayrollPage.enterNewPayeeAllOtherDetails({
      amount: testData.ManagePayrollPayer1.amount,
      transactionCode: testData.ManagePayrollPayer1.transactionCode,
      referenceForPayee: testData.ManagePayrollPayer1.referenceForPayee,
      particulars: testData.ManagePayrollPayer1.particulars,
      paymentDetails: testData.ManagePayrollPayer1.paymentDetails,
      email1: testData.ManagePayrollPayer1.emailId0,
      email2: testData.ManagePayrollPayer1.emailId1,
      email3: testData.ManagePayrollPayer1.emailId2,
      email4: testData.ManagePayrollPayer1.emailId3,
      email5: testData.ManagePayrollPayer1.emailId4,
      emailMessage: testData.ManagePayrollPayer1.emailMessage
    });

    // Step 7: Select Payment date. Click checkbox : Earliest Available Date
    await webComponents.clickWhenVisibleAndEnabled(pages.PayrollPage.earliestAvailableDateCheckbox);

    // Step 8: Click Next button.
    await webComponents.clickWhenVisibleAndEnabled(pages.PayrollPage.nextButton);
    await webComponents.waitForUXLoading([], page);
    await webComponents.waitElementToBeVisible(pages.PayrollPage.submitButton);

    // Step 9: Click Submit button.
    await webComponents.clickWhenVisibleAndEnabled(pages.PayrollPage.submitButton);
    await webComponents.waitForUXLoading([], page);
    await webComponents.waitElementToBeVisible(pages.PayrollPage.finishButton);

    // Step 10: Get the full banner text.
    const referenceText = await pages.PayrollPage.getReferenceText();
    console.log('Captured reference text:', referenceText);
    // It extracts the EBLV… token/Refrence no
    const reference = await pages.PayrollPage.getReferenceID();
    console.log('Captured referenceID:', reference);

    // Step 11: Click Finish button.
    await webComponents.clickWhenVisibleAndEnabled(pages.BulkCollectionPage.finishButton);
    await webComponents.waitForUXLoading([], page);
    await webComponents.waitElementToBeVisible(pages.PayrollPage.payroll);

    // Step 12: Search Reference No and Open.
    await pages.TransferCentersPage.searchAndOpenByReference(reference);
    await webComponents.waitForUXLoading([], page);
    await webComponents.waitElementToBeVisible(pages.PayrollPage.fromAccountViewLabel);
    await webComponents.waitElementToBeVisible(pages.PayrollPage.amountViewLabel);
    await webComponents.waitElementToBeVisible(pages.PayrollPage.hashValueLabel);

    // Step 13: Validate the Reference No details.
    await pages.PayrollPage.validatePayeeOrRefrenceNoDetails({
      fromAccountValue1: testData.ManagePayrollPayee1ValidationData.fromAccountValue1,
      fromAccountValue2: testData.ManagePayrollPayee1ValidationData.fromAccountValue2,
      paymentTypeValue: testData.ManagePayrollPayee1ValidationData.paymentTypeValue,
      amountDeductedValue: testData.ManagePayrollPayee1ValidationData.amountDeductedValue,
      amountDeductedEditedValue: testData.ManagePayrollPayee1ValidationData.amountDeductedEditedValue,

      referenceValueUserProvided: testData.ManagePayrollPayer1.internalReferenceUserProvided,
      batchIdValueUserProvided: testData.ManagePayrollPayer1.batchIdValueUserProvided,

      paymentSummaryLabel: testData.ManagePayrollPayee1ValidationData.paymentSummaryLabel,
      totalPayeesLabel: testData.ManagePayrollPayee1ValidationData.totalPayeesLabel,
      totalPayeesValue: testData.ManagePayrollPayee1ValidationData.totalPayeesValue,
      totalAmountLabel: testData.ManagePayrollPayee1ValidationData.totalAmountLabel,
      totalAmountValue: testData.ManagePayrollPayee1ValidationData.totalAmountValue,
      totalAmountValueEdited: testData.ManagePayrollPayee1ValidationData.totalAmountValueEdited,


      payeeNameLabelValue: testData.ManagePayrollPayer1.newPayeeName,
      payeeNicknameLabelValue: testData.ManagePayrollPayer1.newPayeeNickName,
      bankNameLabelValue: testData.ManagePayrollPayee1ValidationData.bankNameLabelValue,
      bankSwiftBicLabelValue: testData.ManagePayrollPayee1ValidationData.bankSwiftBicLabelValue,
      accountNumberLabelValue: testData.ManagePayrollPayer1.newPayeeAcctNumber,
      statusLabelValue: testData.status.PendingApproval,

      amountLabelValue: testData.ManagePayrollPayer1.amount,
      amountEditedLabelValue: testData.ManagePayrollPayer1.amountEdited,
      transactionLabelValue: testData.ManagePayrollPayee1ValidationData.transactionCodeLabelValue,
      purposeCodeLabelValue: testData.ManagePayrollPayee1ValidationData.purposeCodeLabelValue,

      referenceForPayeeLabelValue: testData.ManagePayrollPayer1.referenceForPayee,
      particularsLabelValue: testData.ManagePayrollPayer1.particulars,

      paymentDetailsLabelValue: testData.ManagePayrollPayer1.paymentDetails,
      emailMessageLabelValue: testData.ManagePayrollPayer1.emailMessage,
      email1LabelValue: testData.ManagePayrollPayer1.emailId0,
      email2LabelValue: testData.ManagePayrollPayer1.emailId1,
      email3LabelValue: testData.ManagePayrollPayer1.emailId2,
      email4LabelValue: testData.ManagePayrollPayer1.emailId3,
      email5LabelValue: testData.ManagePayrollPayer1.emailId4
    }, reference);

    // Step 14: This method deletes the existing opened PayeeOrReferenceNo.
    await pages.BulkCollectionPage.deleteOpenPayerOrReferenceNo({
      transactionDeleted: testData.BulkCollectionValidationData.transactionDeleted,
      internalReference: testData.BulkCollectionValidationData.internalReferenceUserProvided
    }, reference);

  });


});