/**
       * Author: LC5741501
       * Created Date: 03/03/2026
       * This Class "tests/PayTransfer/HK_BulkCollection.spects"
       * Description: This class has one test case.
       * 1) TC001_HK_ManagementPayroll - Create Management Payroll with new change Account number payee
       */

// tests/PayTransfer/HK_ManagementPayroll.spec.ts
import { test, expect } from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
import { NavigatePages, PaymentsPages } from '../../../pages/IDEALX/index';
import { LoginPage } from '../../../pages/IDEALX/LoginPage';

// create lib => components.ts object
const webComponents = new WebComponents();

// internalReferenceBoolean default true 
let internalReferenceBoolean = true;

// amountSGDIsEdit default true 
let amountSGDIsEdit = true;

// yourAccountDeductedEdited default true 
let yourAccountDeductedEdited = true;

// internalReferenceAutoGenerated default true 
let internalReferenceAutoGenerated =true;


// --- Load JSON test data ---
const testDataPath = path.resolve(__dirname, '../../../data/HK_testData.json');
const  testData  = JSON.parse(fs.readFileSync(testDataPath, 'utf-8'));
import { chromium, Browser } from 'playwright';
import { WebComponents } from '../../../lib/components';

let customBrowser: Browser;

const loginCompanyId = testData.ManagePayroll.SIT.loginCompanyId;
const loginUserId    = testData.ManagePayroll.SIT.loginUserIdHKMP;
const fromAccount    = testData.ManagePayroll.SIT.fromAccount;

// Configure retries like the old Protractor suite
test.describe.configure({
  retries: Number(process.env.CASE_RETRY_TIMES ?? 0),
});

test.describe('HK_ManagementPayroll (Playwright using PaymentsPages)', () => {
  let pages: PaymentsPages;
  // Track created payees per test
  type CreatedPayee = { nickName?: string; accountNumber?: string };
  let createdPayees: CreatedPayee[] = [];
   
  /**
   * This method run's before every testcase execution to launch the browser/page
   */ 
  test.beforeEach(async ({ page }, testInfo) => {
    // This is used by the logging proxies in some converted classes (optional)
    process.env.currentTestTitle = testInfo.title;
    customBrowser = await chromium.launch({ headless: false });
    test.setTimeout(200_000);
    const loginPage = new LoginPage(page);
    await loginPage.goto();
    await loginPage.login(loginCompanyId, loginUserId, '123');
    // 2) Create the aggregator once per test
    pages = new PaymentsPages(page);
    
  });

  /**
   * This method run's after every testcase execution to do the 
   * cleanup activity or to close any open connections
   */ 
  test.afterEach(async ({ page }, testInfo) => {
  // Only cleanup if the test passed
  if (testInfo.status !== 'passed') {
    console.warn(`[cleanup] Skipping payee deletion because test status is ${testInfo.status}`);
    return;
    }
    
  // Best-effort cleanup; never fail the test because cleanup failed
  for (const p of createdPayees) {
    try {
      const key = p.nickName ?? p.accountNumber ?? '';
      await pages.PayrollPage.deletePayeeByFilter(key, /* confirm */ true);
      console.log(`[cleanup] Deleted payee with key: ${key}`);
    } catch (err) {
      console.warn('[cleanup] Failed to delete a payee:', err);
    }
  }
  });

  //TC001_HK_ManagementPayroll
  test('TC001_HK_ManagementPayroll - Create Management Payroll with new change Account number payee', async ({ page }) => {
    // Payments → Transfer Center → Payroll
    // paymentMenu => Pay & Transfer (Left option)
    
    await pages.AccountTransferPage.waitForMenu();
    await webComponents.clickWhenVisibleAndEnabledCustomWait(pages.AccountTransferPage.paymentMenu,15_000);

    //Authentication Pop-up 
    await pages.AccountTransferPage.handleAuthIfPresent("1111")

    // Click Payroll option on top
    await webComponents.clickWhenVisibleAndEnabledCustomWait(pages.PayrollPage.managePayroll,15_000);
    await pages.PayrollPage.waitForPayrollFormReady();

    // Step 1: Payment from => Select account from "Account" dropdown
    await webComponents.clickWhenVisibleAndEnabledCustomWait(pages.PayrollPage.fromAccount,15_000);
    await page.keyboard.type(fromAccount);
    await page.keyboard.press('ArrowDown');
    await page.keyboard.press('Enter');

    // Step 2: Payment from => Click "New payee" tab and enters details
    const {accountNumber }  = await pages.PayrollPage.addNewPayeeWithAllDetails({
      name: testData.ManagePayrollPayer1.newPayeeName,
      nickName: testData.ManagePayrollPayer1.newPayeeNickName,
      bankId: testData.ManagePayrollPayer1.payeeBankID,
      accountNumber: testData.ManagePayrollPayer1.newPayeeAcctNumber
    });

    // Register for cleanup
    createdPayees.push({accountNumber });

    //Step 2: Particulars
    await webComponents.enterTextarea(pages.PayrollPage.payeeParticulars, testData.ManagePayrollPayer1.particulars);

    // Step 2: Enter Amount (SGD), Transaction code, Purpose of Payment and other optional details for 
    // Particulars, Collection details to the payer bank, 
    // Message to the payee, Emails, Emails Message
    await pages.PayrollPage.enterNewPayeeAllOtherDetails({
        amount: testData.ManagePayrollPayer1.amount,
        transactionCode: testData.ManagePayrollPayer1.transactionCode,
        referenceForPayee: testData.ManagePayrollPayer1.referenceForPayee,
        particulars: testData.ManagePayrollPayer1.particulars,
        paymentDetails: testData.ManagePayrollPayer1.paymentDetails,
        email1: testData.ManagePayrollPayer1.emailId0,
        email2: testData.ManagePayrollPayer1.emailId1,
        email3: testData.ManagePayrollPayer1.emailId2,
        email4: testData.ManagePayrollPayer1.emailId3,
        email5: testData.ManagePayrollPayer1.emailId4,
        emailMessage: testData.ManagePayrollPayer1.emailMessage
      });

    // Step 3: Payment date
    // Click checkbox : Earliest Available Date
    await webComponents.clickWhenVisibleAndEnabled(pages.PayrollPage.earliestAvailableDateCheckbox);
    
    //Step 4: Payment date : Enter Internal reference = true(It will add the value from Json) , Batch ID
    //await pages.PayrollPage.enterTransactionReferences(testData, internalReferenceBoolean);

    // Click on Next button
    await webComponents.clickWhenVisibleAndEnabled(pages.PayrollPage.nextButton);
    await pages.PayrollPage.waitForPreviewPageReady();

    // Click on Submit button
    await webComponents.clickWhenVisibleAndEnabled(pages.PayrollPage.submitButton);
    await pages.PayrollPage.waitForSubmittedPageReady();

    // It returns the full banner text
    const referenceText = await pages.PayrollPage.getReferenceText();
    console.log('Captured reference text:', referenceText);
    // It extracts the EBLV… token/Refrence no
    const reference = await pages.PayrollPage.getReferenceID();
    console.log('Captured referenceID:', reference);

    // Click on Finish button
    await webComponents.clickWhenVisibleAndEnabled(pages.BulkCollectionPage.finishButton);
    await pages.PayrollPage.waitForPayAndTransferPageReady();
    
    // Search Reference No
    await pages.TransferCentersPage.searchAndOpenByReference(reference);
    await pages.PayrollPage.waitForViewPaymentPageReady();
    
    // This method validates the existing PayeeOrRefrenceNo Details.
    await pages.PayrollPage.validatePayeeOrRefrenceNoDetails({
        fromAccountValue1: testData.ManagePayrollPayee1ValidationData.fromAccountValue1,
        fromAccountValue2: testData.ManagePayrollPayee1ValidationData.fromAccountValue2,
        paymentTypeValue: testData.ManagePayrollPayee1ValidationData.paymentTypeValue,
        amountDeductedValue: testData.ManagePayrollPayee1ValidationData.amountDeductedValue,
        amountDeductedEditedValue: testData.ManagePayrollPayee1ValidationData.amountDeductedEditedValue,

        referenceValueUserProvided: testData.ManagePayrollPayer1.internalReferenceUserProvided,
        batchIdValueUserProvided: testData.ManagePayrollPayer1.batchIdValueUserProvided,
        
        paymentSummaryLabel: testData.ManagePayrollPayee1ValidationData.paymentSummaryLabel,
        totalPayeesLabel: testData.ManagePayrollPayee1ValidationData.totalPayeesLabel,
        totalPayeesValue: testData.ManagePayrollPayee1ValidationData.totalPayeesValue,
        totalAmountLabel: testData.ManagePayrollPayee1ValidationData.totalAmountLabel,
        totalAmountValue: testData.ManagePayrollPayee1ValidationData.totalAmountValue,
        totalAmountValueEdited: testData.ManagePayrollPayee1ValidationData.totalAmountValueEdited,
        
        
        payeeNameLabelValue: testData.ManagePayrollPayer1.newPayeeName,
        payeeNicknameLabelValue: testData.ManagePayrollPayer1.newPayeeNickName,
        bankNameLabelValue: testData.ManagePayrollPayee1ValidationData.bankNameLabelValue,
        bankSwiftBicLabelValue: testData.ManagePayrollPayee1ValidationData.bankSwiftBicLabelValue,
        accountNumberLabelValue: testData.ManagePayrollPayer1.newPayeeAcctNumber,
        statusLabelValue: testData.status.PendingApproval,

        amountLabelValue: testData.ManagePayrollPayer1.amount,
        amountEditedLabelValue: testData.ManagePayrollPayer1.amountEdited,
        transactionLabelValue: testData.ManagePayrollPayee1ValidationData.transactionCodeLabelValue,
        purposeCodeLabelValue: testData.ManagePayrollPayee1ValidationData.purposeCodeLabelValue,

        referenceForPayeeLabelValue: testData.ManagePayrollPayer1.referenceForPayee,
        particularsLabelValue: testData.ManagePayrollPayer1.particulars,

        paymentDetailsLabelValue: testData.ManagePayrollPayer1.paymentDetails,
        emailMessageLabelValue: testData.ManagePayrollPayer1.emailMessage,
        email1LabelValue: testData.ManagePayrollPayer1.emailId0,
        email2LabelValue: testData.ManagePayrollPayer1.emailId1,
        email3LabelValue: testData.ManagePayrollPayer1.emailId2,
        email4LabelValue: testData.ManagePayrollPayer1.emailId3,
        email5LabelValue: testData.ManagePayrollPayer1.emailId4
    },reference);

    //This method deletes the existing opened PayeeOrRefrenceNo Details.
    await pages.BulkCollectionPage.deleteOpenPayerOrReferenceNo(testData, reference);

  });


});