/**
  * Author: LC5741501
  * Created Date: 16/02/26
  * Class path "tests/PayTransfer/SG_Payroll.spec.ts"
  * Description: This Specification contains the test cases related Singapore Payroll Payment.
  * 1) TC001_SGPayroll - Verify creation of a Payroll with new payee
  * 2) TC002_SGPayroll - Verify Payroll can be edited with new payee
  */

import { test, expect } from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
import { NavigatePages, PaymentsPages } from '../../../pages/IDEALX/index';
import { LoginPage } from '../../../pages/IDEALX/LoginPage';
import { CONSTANTS } from '../../../lib/constants';
import { TIMEOUT } from '../../../lib/timeouts';

// create lib => components.ts object
const webComponents = new WebComponents();

// internalReferenceBoolean default true 
let internalReferenceBoolean = true;

// amountSGDIsEdit default true 
let amountSGDIsEdit = true;

// yourAccountDeductedEdited default true 
let yourAccountDeductedEdited = true;

// internalReferenceAutoGenerated default true 
let internalReferenceAutoGenerated = true;


// --- Load JSON test data ---
const testDataPath = path.resolve(__dirname, '../../../data/SG_testData.json');
const testData = JSON.parse(fs.readFileSync(testDataPath, 'utf-8'));
import { chromium, Browser } from 'playwright';
import { WebComponents } from '../../../lib/webComponents';

let customBrowser: Browser;

const loginCompanyId = testData.Payroll.SIT.loginCompanyId;
const loginUserId = testData.Payroll.SIT.loginUserId;
const fromAccount = testData.Payroll.SIT.fromAccount;
const payeeBankID = testData.Payroll.SIT.payeeBankID;

// Configure retries
test.describe.configure({
  retries: Number(process.env.CASE_RETRY_TIMES ?? 0),
});

// Actions for beforEach and afterEach test hooks
test.describe('SG_Payroll (Playwright using PaymentsPages)', { tag: ['@Payroll', '@SG'] }, () => {
  let pages: PaymentsPages;
  // Track created payees per test
  type CreatedPayee = { name?: string; accountNumber?: string };
  let createdPayees: CreatedPayee[] = [];

  /**
  * This method run's before every testcase execution to launch the browser/page
  */
  test.beforeEach(async ({ page }, testInfo) => {
    process.env.currentTestTitle = testInfo.title;

    //customBrowser = await chromium.launch({ headless: false });
    test.setTimeout(TIMEOUT.MAX);
    const loginPage = new LoginPage(page);
    await loginPage.goto();
    await loginPage.login(loginCompanyId, loginUserId, (String(CONSTANTS.PIN)));

    pages = new PaymentsPages(page);
  });

  /**
  * This method run's after every testcase execution to do the 
  * cleanup activity or to close any open connections
  */
  test.afterEach(async ({ page }, testInfo) => {
    // Only cleanup if the test passed
    if (testInfo.status !== 'passed') {
      console.warn(`[cleanup] Skipping payee deletion because test status is ${testInfo.status}`);
      return;
    }

    // Best-effort cleanup; never fail the test because cleanup failed
    for (const p of createdPayees) {
      try {
        const key = p.name ?? p.accountNumber ?? '';
        await pages.PayrollPage.deletePayeeByFilter(key, /* confirm */ true);
        console.log(`[cleanup] Deleted payee with key: ${key}`);
      } catch (err) {
        console.warn('[cleanup] Failed to delete a payee:', err);
      }
    }
  });

  //TC001_SGPayroll
  test('TC001_SGPayroll - Verify creation of a Payroll with new payee', async ({ page }) => {

    //Step 1: Navigate Payment & Transfer Menu.
    await webComponents.waitForUXLoading([], page);
    await webComponents.waitElementToBeVisible(pages.AccountTransferPage.paymentMenu);
    await webComponents.clickWhenVisibleAndEnabled(pages.AccountTransferPage.paymentMenu);

    //Step 2: Handle Authentication Pop-up.
    await webComponents.handleAuthIfPresent(pages.AccountTransferPage.authDialog, pages.AccountTransferPage.securityAccessCode, pages.AccountTransferPage.authenticateButton);

    // Step 3: Click Payroll option.
    await webComponents.clickWhenVisibleAndEnabled(pages.PayrollPage.payroll);
    await webComponents.waitForUXLoading([], page);
    await webComponents.waitElementToBeVisible(pages.PayrollPage.fromAccount);

    // Step 4: Select account from "Account" dropdown.
    await webComponents.clickWhenVisibleAndEnabled(pages.PayrollPage.fromAccount);
    await webComponents.typeTextThroughKeyBoardAction(page, fromAccount);
    await webComponents.pressGivenButtonThroughKeyBoardAction(page, 'ArrowDown');
    await webComponents.pressGivenButtonThroughKeyBoardAction(page, 'Enter');


    // Step 5: Add "New payee".
    const { name, accountNumber } = await pages.PayrollPage.addNewPayeeWithAllDetails({
      name: testData.Payroll.newPayeeName,
      nickName: testData.Payroll.newPayeeNickName,
      bankId: payeeBankID,
      accountNumber: testData.Payroll.newPayeeAcctNumber,
    });

    // Register for cleanup
    createdPayees.push({ name, accountNumber });

    // Step 6: Enter Amount (SGD) and other optional details for 
    // Reference for payee, Payment details to the payee bank, Message to the payee, Email, Email Message
    await pages.PayrollPage.enterNewPayeeAmountAndOptionalDetails({
      amount: testData.Payroll.amount,
      referenceForPayee: testData.Payroll.referenceForPayee,
      paymentDetails: testData.Payroll.paymentDetails,
      emailId0: testData.Payroll.emailId0,
      emailId1: testData.Payroll.emailId1,
      emailId2: testData.Payroll.emailId2,
      emailId3: testData.Payroll.emailId3,
      emailId4: testData.Payroll.emailId4,
      emailMessage: testData.Payroll.emailMessage
    });

    // Step 7: Select Payment date.
    await webComponents.clickWhenVisibleAndEnabled(pages.PayrollPage.earliestAvailableDateCheckbox);

    // Step 8: Enter Internal reference
    await pages.PayrollPage.enterTransactionReferences({
      internalReferenceData: testData.Payroll.internalReference,
      batchIDData: testData.Payroll.batchID
    });

    // Step 9: Click Next button.
    await webComponents.clickWhenVisibleAndEnabled(pages.PayrollPage.nextButton);
    await webComponents.waitForUXLoading([], page);
    await webComponents.waitElementToBeVisible(pages.PayrollPage.submitButton);

    // Step 10: Click Submit button.
    await webComponents.clickWhenVisibleAndEnabled(pages.PayrollPage.submitButton);
    await webComponents.waitForUXLoading([], page);
    await webComponents.waitElementToBeVisible(pages.PayrollPage.finishButton);

    // Step 11: Click Finish button
    await webComponents.clickWhenVisibleAndEnabled(pages.PayrollPage.finishButton);
    await webComponents.waitForUXLoading([], page);
    await webComponents.waitElementToBeVisible(pages.PayrollPage.payroll);

    // Step 12: Search Reference No.
    await pages.TransferCentersPage.searchAndOpenByReference(testData.Payroll.internalReference);
    await webComponents.waitForUXLoading([], page);
    await webComponents.waitElementToBeVisible(pages.PayrollPage.fromAccountViewLabel);
    await webComponents.waitElementToBeVisible(pages.PayrollPage.amountViewLabel);
    await webComponents.waitElementToBeVisible(pages.PayrollPage.hashValueLabel);

    // Step 13: Validate the Reference No details.
    //This method validates the existing PayeeOrRefrenceNo Details.
    await pages.PayrollPage.validatePayeeOrRefrenceNoDetails({

      fromAccountValue1: testData.Payroll.fromAccount1,
      fromAccountValue2: testData.Payroll.fromAccount2,
      paymentTypeValue: testData.Payroll.paymentType,
      amountDeductedValue: testData.Payroll.yourAccountDeducted,
      amountDeductedEditedValue: testData.Payroll.amountDeductedEditedValue,

      referenceValueUserProvided: testData.Payroll.internalReference,
      batchIdValueUserProvided: testData.Payroll.batchID,

      paymentSummaryLabel: testData.Payroll.paymentSummaryLabel,
      totalPayeesLabel: testData.Payroll.totalPayeesLabel,
      totalPayeesValue: testData.Payroll.totalPayeesLabelValue,
      totalAmountLabel: testData.Payroll.totalAmountLabel,
      totalAmountValue: testData.Payroll.totalAmountLabelValue,
      totalAmountValueEdited: testData.Payroll.totalAmountValueEdited,

      payeeNameLabelValue: testData.Payroll.newPayeeName,
      payeeNicknameLabelValue: testData.Payroll.newPayeeNickName,
      bankNameLabelValue: testData.Payroll.bankNameValue,
      bankSwiftBicLabelValue: testData.Payroll.bankSwiftBicValue,
      accountNumberLabelValue: testData.Payroll.newPayeeAcctNumber,
      statusLabelValue: testData.status.PendingApproval,

      amountLabelValue: testData.Payroll.amount,
      amountEditedLabelValue: testData.Payroll.amountEdited,

      transactionLabelValue: testData.Payroll.transactionCodeLabelValue,
      purposeCodeLabelValue: testData.Payroll.purposeCode,

      referenceForPayeeLabelValue: testData.Payroll.referenceForPayee,
      particularsLabelValue: testData.Payroll.particulars,

      paymentDetailsLabelValue: testData.Payroll.paymentDetailsEmpty,
      emailMessageLabelValue: testData.Payroll.emailMessage,
      email1LabelValue: testData.Payroll.emailId0,
      email2LabelValue: testData.Payroll.emailId1,
      email3LabelValue: testData.Payroll.emailId2,
      email4LabelValue: testData.Payroll.emailId3,
      email5LabelValue: testData.Payroll.emailId4

    }, testData.Payroll.internalReference);


    // Step 14: This method deletes the existing opened PayeeOrReferenceNo.
    await pages.PayrollPage.deleteOpenPayeeOrReferenceNo({
      transactionDeleted: testData.Payroll.transactionDeleted,
      internalReference: testData.Payroll.internalReference
    }, testData.Payroll.internalReference);

  });



  //TC002_SGPayroll
  test('TC002_SGPayroll - Verify Payroll can be edited with new payee', async ({ page }) => {

    //Step 1: Navigate Payment & Transfer Menu.
    await webComponents.waitForUXLoading([], page);
    await webComponents.waitElementToBeVisible(pages.AccountTransferPage.paymentMenu);
    await webComponents.clickWhenVisibleAndEnabled(pages.AccountTransferPage.paymentMenu);

    //Step 2: Handle Authentication Pop-up.
    await webComponents.handleAuthIfPresent(pages.AccountTransferPage.authDialog, pages.AccountTransferPage.securityAccessCode, pages.AccountTransferPage.authenticateButton);

    // Step 3: Click Payroll option.
    await webComponents.clickWhenVisibleAndEnabled(pages.PayrollPage.payroll);
    await webComponents.waitForUXLoading([], page);
    await webComponents.waitElementToBeVisible(pages.PayrollPage.fromAccount);

    // Step 4: Select account from "Account" dropdown.
    await webComponents.clickWhenVisibleAndEnabled(pages.PayrollPage.fromAccount);
    await webComponents.typeTextThroughKeyBoardAction(page, fromAccount);
    await webComponents.pressGivenButtonThroughKeyBoardAction(page, 'ArrowDown');
    await webComponents.pressGivenButtonThroughKeyBoardAction(page, 'Enter');

    // Step 5: Add "New payee".
    const { name, accountNumber } = await pages.PayrollPage.addNewPayeeWithAllDetails({
      name: testData.Payroll.newPayeeName,
      nickName: testData.Payroll.newPayeeNickName,
      bankId: payeeBankID,
      accountNumber: testData.Payroll.newPayeeAcctNumber,
    });

    // Register for cleanup
    createdPayees.push({ name, accountNumber });

    // Step 6:  Enter Amount (SGD) and other optional details for 
    // Reference for payee, Payment details to the payee bank, Message to the payee, Email, Email Message
    await pages.PayrollPage.enterNewPayeeAmountAndOptionalDetails({
      amount: testData.Payroll.amount,
      referenceForPayee: testData.Payroll.referenceForPayee,
      paymentDetails: testData.Payroll.paymentDetails,
      emailId0: testData.Payroll.emailId0,
      emailId1: testData.Payroll.emailId1,
      emailId2: testData.Payroll.emailId2,
      emailId3: testData.Payroll.emailId3,
      emailId4: testData.Payroll.emailId4,
      emailMessage: testData.Payroll.emailMessage
    });

    // Step 7: Select Payment date.
    await webComponents.clickWhenVisibleAndEnabled(pages.PayrollPage.earliestAvailableDateCheckbox);

    // Step 8: Enter Internal reference= Enter Internal reference = true(It will add the value from Json) , Batch ID
    await pages.PayrollPage.enterTransactionReferences({
      internalReferenceData: testData.Payroll.internalReferenceAutoYes,
      batchIDData: testData.Payroll.batchID
    });

    // Step 9: Click Next button.
    await webComponents.clickWhenVisibleAndEnabled(pages.PayrollPage.nextButton);
    await webComponents.waitForUXLoading([], page);
    await webComponents.waitElementToBeVisible(pages.PayrollPage.submitButton);

    // Step 10: Click Submit button.
    await webComponents.clickWhenVisibleAndEnabled(pages.PayrollPage.submitButton);
    await webComponents.waitForUXLoading([], page);
    await webComponents.waitElementToBeVisible(pages.PayrollPage.finishButton);

    // Step 11: Get Reference No.
    const referenceText = await pages.PayrollPage.getReferenceText();
    console.log('Captured reference text:', referenceText);
    // It Extract the reference no EBLV… token:
    const reference = await pages.PayrollPage.getReferenceID();
    console.log('Captured referenceID:', reference);

    // Step 12: Click Finish button
    await webComponents.clickWhenVisibleAndEnabled(pages.PayrollPage.finishButton);
    await webComponents.waitForUXLoading([], page);
    await webComponents.waitElementToBeVisible(pages.PayrollPage.payroll);

    // Step 13: Search and open Reference No details.
    await pages.TransferCentersPage.searchAndOpenByReference(reference);
    await webComponents.waitForUXLoading([], page);
    await webComponents.waitElementToBeVisible(pages.PayrollPage.fromAccountViewLabel);
    await webComponents.waitElementToBeVisible(pages.PayrollPage.amountViewLabel);
    await webComponents.waitElementToBeVisible(pages.PayrollPage.hashValueLabel);

    // Step 14: Validate the Reference No details.
    //This method validates the existing PayeeOrRefrenceNo Details.
    await pages.PayrollPage.validatePayeeOrRefrenceNoDetails({

      fromAccountValue1: testData.Payroll.fromAccount1,
      fromAccountValue2: testData.Payroll.fromAccount2,
      paymentTypeValue: testData.Payroll.paymentType,
      amountDeductedValue: testData.Payroll.yourAccountDeducted,
      amountDeductedEditedValue: testData.Payroll.amountDeductedEditedValue,

      referenceValueUserProvided: testData.Payroll.internalReferenceAutoYes,
      batchIdValueUserProvided: testData.Payroll.batchID,

      paymentSummaryLabel: testData.Payroll.paymentSummaryLabel,
      totalPayeesLabel: testData.Payroll.totalPayeesLabel,
      totalPayeesValue: testData.Payroll.totalPayeesLabelValue,
      totalAmountLabel: testData.Payroll.totalAmountLabel,
      totalAmountValue: testData.Payroll.totalAmountLabelValue,
      totalAmountValueEdited: testData.Payroll.totalAmountValueEdited,

      payeeNameLabelValue: testData.Payroll.newPayeeName,
      payeeNicknameLabelValue: testData.Payroll.newPayeeNickName,
      bankNameLabelValue: testData.Payroll.bankNameValue,
      bankSwiftBicLabelValue: testData.Payroll.bankSwiftBicValue,
      accountNumberLabelValue: testData.Payroll.newPayeeAcctNumber,
      statusLabelValue: testData.status.PendingApproval,

      amountLabelValue: testData.Payroll.amount,
      amountEditedLabelValue: testData.Payroll.amountEdited,

      transactionLabelValue: testData.Payroll.transactionCodeLabelValue,
      purposeCodeLabelValue: testData.Payroll.purposeCode,

      referenceForPayeeLabelValue: testData.Payroll.referenceForPayee,
      particularsLabelValue: testData.Payroll.particulars,

      paymentDetailsLabelValue: testData.Payroll.paymentDetailsEmpty,
      emailMessageLabelValue: testData.Payroll.emailMessage,
      email1LabelValue: testData.Payroll.emailId0,
      email2LabelValue: testData.Payroll.emailId1,
      email3LabelValue: testData.Payroll.emailId2,
      email4LabelValue: testData.Payroll.emailId3,
      email5LabelValue: testData.Payroll.emailId4

    }, reference);

    // Step 15: Edit the Amount.
    await pages.PayrollPage.editAmountSGD(testData);

    // Step 16: Click Next button.
    await webComponents.clickWhenVisibleAndEnabled(pages.PayrollPage.nextButton);
    await webComponents.waitForUXLoading([], page);
    await webComponents.waitForUXLoading([], page);
    await webComponents.waitElementToBeVisible(pages.PayrollPage.submitButton);

    // Step 17: Click Submit button.
    await webComponents.clickWhenVisibleAndEnabled(pages.PayrollPage.submitButton);
    await webComponents.waitForUXLoading([], page);
    await webComponents.waitElementToBeVisible(pages.PayrollPage.finishButton);

    // Step 18: Click Finish button
    await webComponents.clickWhenVisibleAndEnabled(pages.PayrollPage.finishButton);
    await webComponents.waitForUXLoading([], page);
    await webComponents.waitElementToBeVisible(pages.PayrollPage.payroll);

    // Step 19: Search and open Reference No details.
    await pages.TransferCentersPage.searchAndOpenByReference(reference);
    await webComponents.waitForUXLoading([], page);
    await webComponents.waitElementToBeVisible(pages.PayrollPage.fromAccountViewLabel);
    await webComponents.waitElementToBeVisible(pages.PayrollPage.amountViewLabel);
    await webComponents.waitElementToBeVisible(pages.PayrollPage.hashValueLabel);

    // Step 20: Validate the Reference No details with Edited Amount
    await pages.PayrollPage.validatePayeeOrRefrenceNoDetails({

      fromAccountValue1: testData.Payroll.fromAccount1,
      fromAccountValue2: testData.Payroll.fromAccount2,
      paymentTypeValue: testData.Payroll.paymentType,
      amountDeductedValue: testData.Payroll.yourAccountDeductedEdited,
      amountDeductedEditedValue: testData.Payroll.yourAccountDeductedEdited,

      referenceValueUserProvided: testData.Payroll.internalReferenceAutoYes,
      batchIdValueUserProvided: testData.Payroll.batchID,

      paymentSummaryLabel: testData.Payroll.paymentSummaryLabel,
      totalPayeesLabel: testData.Payroll.totalPayeesLabel,
      totalPayeesValue: testData.Payroll.totalPayeesLabelValue,
      totalAmountLabel: testData.Payroll.totalAmountLabel,
      totalAmountValue: testData.Payroll.totalAmountLabelValue,
      totalAmountValueEdited: testData.Payroll.totalAmountLabelValueEdited,

      payeeNameLabelValue: testData.Payroll.newPayeeName,
      payeeNicknameLabelValue: testData.Payroll.newPayeeNickName,
      bankNameLabelValue: testData.Payroll.bankNameValue,
      bankSwiftBicLabelValue: testData.Payroll.bankSwiftBicValue,
      accountNumberLabelValue: testData.Payroll.newPayeeAcctNumber,
      statusLabelValue: testData.status.PendingApproval,

      amountLabelValue: testData.Payroll.amount,
      amountEditedLabelValue: testData.Payroll.editAmount,

      transactionLabelValue: testData.Payroll.transactionCodeLabelValue,
      purposeCodeLabelValue: testData.Payroll.purposeCode,

      referenceForPayeeLabelValue: testData.Payroll.referenceForPayee,
      particularsLabelValue: testData.Payroll.particulars,

      paymentDetailsLabelValue: testData.Payroll.paymentDetailsEmpty,
      emailMessageLabelValue: testData.Payroll.emailMessage,
      email1LabelValue: testData.Payroll.emailId0,
      email2LabelValue: testData.Payroll.emailId1,
      email3LabelValue: testData.Payroll.emailId2,
      email4LabelValue: testData.Payroll.emailId3,
      email5LabelValue: testData.Payroll.emailId4

    }, reference);

    // Step 21: This method deletes the existing opened PayeeOrReferenceNo.
    await pages.PayrollPage.deleteOpenPayeeOrReferenceNo({
      transactionDeleted: testData.Payroll.transactionDeleted,
      internalReference: testData.Payroll.internalReferenceAutoYes
    }, reference);

  });
});
