/**
       * Author: LC5741501
       * Created Date: 16/02/26
       * This Class "tests/PayTransfer/SG_Payroll.spec.ts"
       * Description: This class has two test cases.
       * 1) TC001_SGPayroll - Create SG Payroll Alternate with new payee
       * 2) TC002_SGPayroll - Edit Payroll Alternate via Transfer Center
       */

// tests/PayTransfer/SG_Payroll.spec.ts
import { test, expect } from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
import { NavigatePages, PaymentsPages } from '../../../pages/IDEALX/index';
import { LoginPage } from '../../../pages/IDEALX/LoginPage';

// create lib => components.ts object
const webComponents = new WebComponents();

// internalReferenceBoolean default true 
let internalReferenceBoolean = true;

// amountSGDIsEdit default true 
let amountSGDIsEdit = true;

// yourAccountDeductedEdited default true 
let yourAccountDeductedEdited = true;

// internalReferenceAutoGenerated default true 
let internalReferenceAutoGenerated =true;


// --- Load JSON test data ---
const testDataPath = path.resolve(__dirname, '../../../data/SG_testData.json');
const  testData  = JSON.parse(fs.readFileSync(testDataPath, 'utf-8'));
import { chromium, Browser } from 'playwright';
import { WebComponents } from '../../../lib/components';

let customBrowser: Browser;

const loginCompanyId = testData.Payroll.SIT.loginCompanyId;
const loginUserId    = testData.Payroll.SIT.loginUserId;
const fromAccount    = testData.Payroll.SIT.fromAccount;
const payeeBankID    = testData.Payroll.SIT.payeeBankID;

// Configure retries like the old Protractor suite
test.describe.configure({
  retries: Number(process.env.CASE_RETRY_TIMES ?? 0),
});

test.describe('SG_Payroll (Playwright using PaymentsPages)', () => {
  let pages: PaymentsPages;
  // Track created payees per test
  type CreatedPayee = { nickName?: string; accountNumber?: string };
  let createdPayees: CreatedPayee[] = [];
   
  /**
   * This method run's before every testcase execution to launch the browser/page
   */ 
  test.beforeEach(async ({ page }, testInfo) => {
    // This is used by the logging proxies in some converted classes (optional)
    process.env.currentTestTitle = testInfo.title;
    customBrowser = await chromium.launch({ headless: false });
    test.setTimeout(200_000);
    const loginPage = new LoginPage(page);
    await loginPage.goto();
    await loginPage.login(loginCompanyId, loginUserId, '123');
    // 2) Create the aggregator once per test
    pages = new PaymentsPages(page);
    
  });

  /**
   * This method run's after every testcase execution to do the 
   * cleanup activity or to close any open connections
   */ 
  test.afterEach(async ({ page }, testInfo) => {
  // Only cleanup if the test passed
  if (testInfo.status !== 'passed') {
    console.warn(`[cleanup] Skipping payee deletion because test status is ${testInfo.status}`);
    return;
    }
    
  // Best-effort cleanup; never fail the test because cleanup failed
  for (const p of createdPayees) {
    try {
      const key = p.nickName ?? p.accountNumber ?? '';
      await pages.PayrollPage.deletePayeeByFilter(key, /* confirm */ true);
      console.log(`[cleanup] Deleted payee with key: ${key}`);
    } catch (err) {
      console.warn('[cleanup] Failed to delete a payee:', err);
    }
  }
  });

  //TC001_SGPayroll
  test('TC001_SGPayroll - Create Payroll Alternate with new payee', async ({ page }) => {
    // Payments → Transfer Center → Payroll
    // paymentMenu => Pay & Transfer (Left option)
    
    await pages.AccountTransferPage.waitForMenu();
    await webComponents.clickWhenVisibleAndEnabledCustomWait(pages.AccountTransferPage.paymentMenu,15_000);

    //Authentication Pop-up 
    await pages.AccountTransferPage.handleAuthIfPresent("1111")

    // Click Payroll option on top
    await webComponents.clickWhenVisibleAndEnabledCustomWait(pages.PayrollPage.payroll,15_000);
    await pages.PayrollPage.waitForPayrollFormReady();

    // Step 1: Payment from => Select account from "Account" dropdown
    await webComponents.clickWhenVisibleAndEnabledCustomWait(pages.PayrollPage.fromAccount,15_000);
    await page.keyboard.type(fromAccount);
    await page.keyboard.press('ArrowDown');
    await page.keyboard.press('Enter');

    // Step 2: Payment from => Click "New payee" tab and enters details
    const { nickName, accountNumber }  = await pages.PayrollPage.addNewPayeeWithAllDetails({
      name: testData.Payroll.newPayeeName,
      nickName: testData.Payroll.newPayeeNickName,
      bankId: payeeBankID,
      accountNumber: testData.Payroll.newPayeeAcctNumber,
    });

    // Register for cleanup
    createdPayees.push({ nickName, accountNumber });

    // Step 2: Enter Amount (SGD) and other optional details for 
    // Reference for payee, Payment details to the payee bank, 
    // Message to the payee, Email, Email Message
    await pages.PayrollPage.enterNewPayeeAmountAndOptionalDetails(testData);

    // Step 3: Payment date

    // Click checkbox : Earliest Available Date
    await webComponents.clickWhenVisibleAndEnabled(pages.PayrollPage.earliestAvailableDateCheckbox);
    
    //Step 4: Payment date : Enter Internal reference = true(It will add the value from Json) , Batch ID
    await pages.PayrollPage.enterTransactionReferences(testData, internalReferenceBoolean);

    // Click on Next button
    await webComponents.clickWhenVisibleAndEnabled(pages.PayrollPage.nextButton);
    await pages.PayrollPage.waitForPreviewPageReady();

    // Click on Submit button
    await webComponents.clickWhenVisibleAndEnabled(pages.PayrollPage.submitButton);
    await pages.PayrollPage.waitForSubmittedPageReady();

    // Click on Finish button
    await webComponents.clickWhenVisibleAndEnabled(pages.PayrollPage.finishButton);
    await pages.PayrollPage.waitForPayAndTransferPageReady();

    // Search Reference No in Transfer Center
    await pages.TransferCentersPage.searchAndOpenByReference(testData.Payroll.internalReference);
    await pages.PayrollPage.waitForViewPaymentPageReady();
    
    //This method validates the existing PayeeOrRefrenceNo Details.
    await pages.PayrollPage.validatePayeeOrRefrenceNoDetailsOfPayroll(testData,internalReferenceAutoGenerated=false, testData.Payroll.internalReference, amountSGDIsEdit=false, yourAccountDeductedEdited=false);
    
    //This method deletes the existing opened PayeeOrRefrenceNo Details.
    await pages.PayrollPage.deleteOpenPayeeOrReferenceNo(testData,internalReferenceAutoGenerated=false, testData.Payroll.internalReference);

  });


  //TC002_SGPayroll
  test('TC002_SGPayroll - Edit Payroll Alternate via Transfer Center', async ({ page }) => {
    // Payments → Transfer Center → Payroll
    // paymentMenu => Pay & Transfer (Left option)
    
    await pages.AccountTransferPage.waitForMenu();
    await webComponents.clickWhenVisibleAndEnabledCustomWait(pages.AccountTransferPage.paymentMenu,15_000);

    //Authentication Pop-up 
    await pages.AccountTransferPage.handleAuthIfPresent("1111")

    // Click Payroll option on top
    await webComponents.clickWhenVisibleAndEnabledCustomWait(pages.PayrollPage.payroll,15_000);
    await pages.PayrollPage.waitForPayrollFormReady();

    // Step 1: Payment from => Select account from "Account" dropdown
    await webComponents.clickWhenVisibleAndEnabledCustomWait(pages.PayrollPage.fromAccount,15_000);
    await page.keyboard.type(fromAccount);
    await page.keyboard.press('ArrowDown');
    await page.keyboard.press('Enter');

    // Step 2: Payment from => Click "New payee" tab and enters details
    const { nickName, accountNumber }  = await pages.PayrollPage.addNewPayeeWithAllDetails({
      name: testData.Payroll.newPayeeName,
      nickName: testData.Payroll.newPayeeNickName,
      bankId: payeeBankID,
      accountNumber: testData.Payroll.newPayeeAcctNumber,
    });

    // Register for cleanup
    createdPayees.push({ nickName, accountNumber });

    // Step 2: Enter Amount (SGD) and other optional details for 
    // Reference for payee, Payment details to the payee bank, 
    // Message to the payee, Email, Email Message
    await pages.PayrollPage.enterNewPayeeAmountAndOptionalDetails(testData);

    // Step 3: Payment date

    // Click checkbox : Earliest Available Date
    await webComponents.clickWhenVisibleAndEnabled(pages.PayrollPage.earliestAvailableDateCheckbox);
    
    //Step 4: Payment date : Enter Internal reference = true(It will add the value from Json) , Batch ID
    await pages.PayrollPage.enterTransactionReferences(testData, internalReferenceBoolean=false);

    // Click on Next button
    await webComponents.clickWhenVisibleAndEnabled(pages.PayrollPage.nextButton);
    await pages.PayrollPage.waitForPreviewPageReady();

    // Click on Submit button
    await webComponents.clickWhenVisibleAndEnabled(pages.PayrollPage.submitButton);
    await pages.PayrollPage.waitForSubmittedPageReady();

    // Its capture the full banner text:
    const referenceText = await pages.PayrollPage.getReferenceText();
    console.log('Captured reference text:', referenceText);
    // It Extract the reference no EBLV… token:
    const reference = await pages.PayrollPage.getReferenceID();
    console.log('Captured referenceID:', reference);

    // Click on Finish button
    await webComponents.clickWhenVisibleAndEnabled(pages.PayrollPage.finishButton);
    await pages.PayrollPage.waitForPayAndTransferPageReady();

    // Find it again in Transfer Center by reference
    await pages.TransferCentersPage.searchAndOpenByReference(reference);
    await pages.PayrollPage.waitForViewPaymentPageReady();
    
    // This method validates the existing PayeeOrRefrenceNo Details.
    await pages.PayrollPage.validatePayeeOrRefrenceNoDetailsOfPayroll(testData,internalReferenceAutoGenerated, reference, amountSGDIsEdit=false, yourAccountDeductedEdited=false);

    await pages.PayrollPage.editAmountSGD(testData);

    // Click on Next button
    await webComponents.clickWhenVisibleAndEnabled(pages.PayrollPage.nextButton);
    await pages.PayrollPage.waitForPreviewPageReady();

    // Click on Submit button
    await webComponents.clickWhenVisibleAndEnabled(pages.PayrollPage.submitButton);
    await pages.PayrollPage.waitForSubmittedPageReady();

    // Click on Finish button
    await webComponents.clickWhenVisibleAndEnabled(pages.PayrollPage.finishButton);
    await pages.PayrollPage.waitForPayAndTransferPageReady();

    // Find it again in Transfer Center by reference
    await pages.TransferCentersPage.searchAndOpenByReference(reference);
    await pages.PayrollPage.waitForViewPaymentPageReady();

    // This method validates the existing PayeeOrRefrenceNo Details. Validates values after editing the Amount..
    await pages.PayrollPage.validatePayeeOrRefrenceNoDetailsOfPayroll(testData,internalReferenceAutoGenerated, reference,amountSGDIsEdit=true,yourAccountDeductedEdited=true);
    
    //This method deletes the existing opened PayeeOrRefrenceNo Details.
    await pages.PayrollPage.deleteOpenPayeeOrReferenceNo(testData,internalReferenceAutoGenerated, reference);

  });


});
